config/routes.rb
Uebung7::Application.routes.draw do
  resources :projects, except: [:show]
  devise_for :users
  resources :tasks, except: [:show]
  root 'tasks#index'
  









end

app/models/project.rb
class Project < ActiveRecord::Base

  has_many :tasks
  
  validates :name, presence: true, uniqueness: true
  
  
end

app/models/task.rb
class Task < ActiveRecord::Base
  
  belongs_to :user
  belongs_to :project
  belongs_to :delegated, class_name: "User", foreign_key: "delegated_id"
  
  validates :name, presence: true
  validates :deadline, presence: true
  validates :duration, presence: true, numericality: true 
  
  def is_delayed?
   self.deadline < Date.today
  end

  
  def distance_from_now_in_days
    (self.deadline - Date.today).to_i     
  end


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  
  has_many :tasks
  has_many :delegated_tasks, class_name: "Task", foreign_key: "delegated_id"
  
  validates :username, presence:  true, uniqueness: true
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?
  
  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
 
 before_action :authenticate_user!
 
  def index
    @projects = Project.all
  end
  
  def new
    @project = Project.new
  end

   def create
    @project = Project.new(project_params)
    if !@project.save
      render action: 'error'
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
  end
  
  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    if !@project.update(project_params)
      render action: 'error'
    end
  end

private

    def project_params
      params.require(:project).permit(:name)
    end 

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_task, only: [:edit, :update, :destroy]

  

  # GET /tasks
  # GET /tasks.json
  def index
    if params[:sorting]
      @done = Task.where(done: true).order(params[:sorting] => :desc)
      @todo = Task.where(done: false).order(params[:sorting] => :desc)
    else
       @done = Task.where(done: true).order(created_at: :desc)
       @todo = Task.where(done: false).order(updated_at: :desc)
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  
  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    
    @task = current_user.tasks.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to tasks_url, notice: 'Task was successfully created.' }
        format.json { render action: 'show', status: :created, location: @task }
      else
        format.html { render action: 'new' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to tasks_url, notice: 'Task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
       
      if @task.user_id != current_user.id && @task.delegated_id != current_user.id
        redirect_to tasks_url, alert: 'You can edit only your own Tasks.'
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name, :deadline, :done, :duration, :delegated_id, :project_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_messages.html.erb
 <% if notice %> 
  		<p id="notice" class="alert alert-success alert-dismissable fade in" data-dismiss="alert" aria-hidden="true">
   		 <%= notice %>
  		<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
 		 </p>
	<% end %>

<% if alert %> 
  <p id="notice" class="alert alert-danger alert-dismissable fade in" data-dismiss="alert" aria-hidden="true">
    <%= alert %>
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  </p>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <%= link_to "Todo-App", tasks_path, :class => "navbar-brand" %>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
          <li class="<%= "active" if params[:controller] == "tasks" %>">
            <%= link_to "Tasks", tasks_path %>
          </li>
          <li class="<%= "active" if params[:controller] == "projects" %>">
            <%= link_to "Projects", projects_path %>
          </li>
        </ul>

            <ul class="nav navbar-nav navbar-right">
                <% if user_signed_in? %>
                <li>
                    <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>
                </li>
                <li>
                    <%= link_to "Logged in as " + current_user.username, edit_user_registration_path %> 
                </li>
                <% else %>
                <li>
                    <%= link_to 'Login', new_user_session_path %>
                </li>
                <li>
                    <%= link_to 'Sign up', new_user_registration_path %>
                </li>
                <% end %>
            </ul>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	
  <title>Uebung7</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/navigation' %>

<div class="container">
	<%= render 'layouts/messages' %>
    <%= yield %>
</div> <!-- /container -->

</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project, remote: true, :html => {id: "new_project"}) do |f| %>
    <div class="row form-group">
        <div class="col-xs-4">
            <label class="control-label" for="project_name" id="error-message"></label>
            <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="col-xs-3 button-group"> 
            <%= f.submit "Save", class: "btn btn-primary btn-sm" %>  
            <%= link_to 'Cancel', "", id: "cancel_button", class: "btn btn-default btn-sm" %>
        </div>
    </div>
<% end %>

app/views/projects/_project.html.erb
<tr id="project_<%= project.id %>"> 
  <td><%= link_to project.name, edit_project_path(project), remote: true %></td>

  <td><%= link_to "Delete", project, :class => "btn btn-danger  btn-sm", remote: true, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/projects/create.js.erb


$('#new_project').remove();
$('#new_link').show();
$('tbody').append('<%= j render(@project) %>');

$('#project_<%= @project.id %>').effect("highlight");

app/views/projects/destroy.js.erb
$('#new_project').remove();
$('#new_link').show();
$('#project_<%= @project.id %>').remove();

app/views/projects/edit.js.erb
$('#new_project').remove();
$('#new_link').hide().after('<%= j render("form") %>');
$('#project_name').focus();
$('#cancel_button').clickCancelButton();

app/views/projects/error.js.erb
$(".form-group").addClass("has-error");
$("#error-message").html("<%= j @project.errors.full_messages[0] %>");

$("#new_project").effect("shake");

app/views/projects/index.html.erb
<h2>Projects</h2>
<%= link_to 'New Project', new_project_path, id: "new_link", remote: true, :class => "btn btn-success  btn-sm" %>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= render @projects %>
  </tbody>
</table>

app/views/projects/new.js.erb

$('#new_link').hide().after('<%= j render("form") %>');
$('#project_name').focus();
$('#cancel_button').clickCancelButton();

app/views/projects/update.js.erb
$('#new_project').remove();
$('#new_link').show();
$('#project_<%= @project.id %>').replaceWith('<%= j render(@project) %>');

$('#project_<%= @project.id %>').effect("highlight");

app/views/tasks/_form.html.erb
<%= form_for @task, :html => { :role => "form"} do |f| %>
    
  <% if @task.errors.any? %>
    <div class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
          <% @task.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

 <div class="checkbox">
    <label>
      <%= f.check_box :done %> <%= f.label :done %>
    </label>
  </div>
  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control", placeholder: "Name of Task" %>
  </div>
  <div class="form-group">
    <%= f.label :deadline %><br>
    <%= f.date_field :deadline, class: "form-control", placeholder: "Deadline of Task" %>
  </div>
  <div class="form-group">
    <%= f.label :duration %><br>
    <%= f.text_field :duration, class: "form-control", placeholder: "Duration of Task" %>
  </div>
  <div class="form-group">
  <%= f.label :delegated_id %><br>
  <%= f.select :delegated_id, User.all.collect {|u| [ u.username, u.id ] }, { :include_blank => true, :selected => @task.delegated_id}, class: "form-control" %>
</div>  
  <div class="form-group">
    <%= f.label :project_id %><br>
    <%= f.select :project_id, Project.all.collect {|p| [ p.name, p.id ] }, { :include_blank => true, :selected => @task.project_id}, class: "form-control" %>
	</div>
  <div class="actions">
    <%= f.submit "Save Task", class: "btn btn-primary" %>  <%= link_to 'Cancel', tasks_path, class: "btn btn-default" %>
  </div>    
<%end%>

app/views/tasks/_table.html.erb

<table class="table  table-hover">  
  <thead>
    <tr>
      <th></th>
      <th>Name</th>
      <th>Project</th>
      <th>Created</th>
      <th>Delegated</th>
      
	  <th>
			<% if params[:sorting] == "deadline" %>
  			Deadline ^
			<% else %>
  			<%= link_to "Deadline", tasks_path(sorting: "deadline") %>
			<% end %>
	  </th>
	  <th>
			<% if params[:sorting] == "duration" %>
  			Duration ^
			<% else %>
  			<%=	link_to "Duration", tasks_path(sorting: "duration") %>
			<% end %> 
	  </th>
      <th></th>
    </tr>
  </thead>


  
  <tbody>
    <% tasks.each do |task| %>
      <tr>
      	<td>
  			<%= form_for task do |f| %>
    		<%= f.check_box :done, class: "checkable" %>
  			<% end %>
		</td>
        <td class="<%= css_class %>"><%= link_to task.name, edit_task_path(task) %></td>
        <td> <%= task.project.name if task.project %> </td>
        <td> <%= task.user.username %> </td>
         <td>
	      <%= "in " if !task.is_delayed? %> 
	      <%= pluralize(task.distance_from_now_in_days.abs, "Day")  %>
	      <%= " ago " if task.is_delayed? %> 
	    </td>
        <td><%= task.duration %></td>
        <td><%= link_to 'Destroy', task, class: "btn btn-danger btn-sm", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>

  </tbody>
  
  
  
  
</table>




app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb


<%= link_to 'New Task', new_task_path, class: "btn btn-success btn-sm" %>

<h2>Todo (<%= pluralize(@todo.count, "Task") %>, <%= pluralize(@todo.sum("duration"), "Hour") %>)</h2>
<%= render partial: "table", locals: {tasks: @todo, css_class: "todo"} %>
<h2>Done (<%= pluralize(@done.count, "Task") %>, <%= pluralize(@done.sum("duration"), "Hour") %>)</h2>
<%= render partial: "table", locals: {tasks: @done, css_class: "done"} %>

<br>
  
  
    

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>